"use client";

import Image from "next/image";
import { motion } from "framer-motion";
import { ArrowRight, Check, Mail, MapPin, Phone, Sparkles } from "lucide-react";
import { FormEvent, useState } from "react";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";

export default function ContactPage() {
  const [submitted, setSubmitted] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitted(true); }
  return <main className="min-h-screen bg-[#F0F2F5] text-[#1C1E21]">
    <SiteHeader/>
    <section className="relative overflow-hidden border-b border-[#1C1E21]/10 bg-white pt-24"><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(rgba(24,119,242,.07)_1px,transparent_1px),linear-gradient(90deg,rgba(24,119,242,.07)_1px,transparent_1px)] [background-size:64px_64px]"/><div className="section-shell relative grid min-h-[570px] items-center gap-10 py-14 lg:grid-cols-[.95fr_1.05fr]"><motion.div initial={{opacity:0,y:25}} animate={{opacity:1,y:0}}><p className="flex items-center gap-2 text-sm font-semibold uppercase tracking-[.2em] text-[#1877F2]"><Sparkles className="h-4 w-4"/>Start a conversation</p><h1 className="mt-6 text-balance text-5xl font-semibold leading-[1.02] md:text-7xl">Get in touch <span className="text-[#1877F2]">with us.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#1C1E21]/60">Ready to take your project to the next level? Whether you have questions, want to discuss ideas, or are ready to get started, we&apos;d love to hear from you.</p><div className="mt-9 space-y-4"><a href="tel:+13466904693" className="flex items-center gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#E7F3FF] text-[#1877F2]"><Phone className="h-5 w-5"/></span><span><small className="block text-[#1C1E21]/45">Call now</small><b>+1 (346) 690-4693</b></span></a><a href="mailto:contact@opusgeeks.com" className="flex items-center gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#E7F3FF] text-[#1877F2]"><Mail className="h-5 w-5"/></span><span><small className="block text-[#1C1E21]/45">Email now</small><b>contact@opusgeeks.com</b></span></a></div></motion.div><motion.div initial={{opacity:0,x:35}} animate={{opacity:1,x:0}} className="relative h-[450px]"><Image src="/images/contact-main.png" alt="Contact Opus Geeks" fill priority className="object-contain drop-shadow-[0_28px_48px_rgba(28,30,33,.18)]"/></motion.div></div></section>

    <section className="py-20 md:py-28"><div className="section-shell grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#1877F2]">Book a free consultation</p><h2 className="mt-4 text-balance text-4xl font-semibold md:text-6xl">Tell us what you&apos;re building.</h2><p className="mt-6 text-lg leading-8 text-[#1C1E21]/55">Share your goals, timeline, and product idea. Our team will review the details and help shape a practical next step.</p><div className="relative mt-8 h-56 overflow-hidden rounded-2xl bg-white"><Image src="/images/contact-why.png" alt="Opus Geeks consultation" fill className="object-cover"/></div></div><div className="rounded-2xl border border-[#1C1E21]/10 bg-white p-6 shadow-[0_20px_60px_rgba(28,30,33,.08)] md:p-10">{submitted?<div className="flex min-h-[480px] flex-col items-center justify-center text-center"><span className="flex h-16 w-16 items-center justify-center rounded-full bg-[#E7F3FF] text-[#1877F2]"><Check className="h-8 w-8"/></span><h3 className="mt-6 text-3xl font-semibold">Request received.</h3><p className="mt-3 max-w-md text-[#1C1E21]/55">Thank you. The Opus Geeks team will review your project and contact you shortly.</p><button onClick={()=>setSubmitted(false)} className="mt-7 rounded-full bg-[#1877F2] px-6 py-3 font-semibold text-white">Send another request</button></div>:<form onSubmit={submit} className="grid gap-5 sm:grid-cols-2"><Field label="Full name" name="name"/><Field label="Work email" name="email" type="email"/><Field label="Phone number" name="phone" type="tel"/><label className="block"><span className="mb-2 block text-sm font-medium">Service</span><select required name="service" className="h-[50px] w-full rounded-xl border border-[#1C1E21]/12 bg-[#F0F2F5] px-4 outline-none focus:border-[#1877F2]"><option value="">Select a service</option><option>App Development</option><option>Web Development</option><option>UX/UI Design</option><option>Other</option></select></label><label className="block sm:col-span-2"><span className="mb-2 block text-sm font-medium">Project description</span><textarea required rows={5} name="description" placeholder="Goals, features, timeline, or anything useful..." className="w-full resize-none rounded-xl border border-[#1C1E21]/12 bg-[#F0F2F5] px-4 py-3 outline-none focus:border-[#1877F2]"/></label><label className="flex items-start gap-3 text-sm text-[#1C1E21]/55 sm:col-span-2"><input required type="checkbox" className="mt-1 accent-[#1877F2]"/>I agree to be contacted about this project.</label><button className="group flex items-center justify-center gap-3 rounded-xl bg-[#1877F2] px-6 py-4 font-semibold text-white sm:col-span-2">Submit request <ArrowRight className="h-5 w-5 transition group-hover:translate-x-1"/></button></form>}</div></div></section>

    <section className="bg-white py-20 md:py-24"><div className="section-shell grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#1877F2]">Why choose us</p><h2 className="mt-4 text-balance text-4xl font-semibold md:text-6xl">Digital delivery built around your goals.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-[#1C1E21]/60">We deliver solutions tailored to your unique needs. Expertise, dedication to excellence, and a client-centric approach help every project move beyond expectations.</p></div><div className="grid grid-cols-2 overflow-hidden rounded-2xl border border-[#1C1E21]/10">{[["01","Clear strategy"],["02","Senior execution"],["03","Visible progress"],["04","Reliable support"]].map(([n,label])=><div key={n} className="border-b border-r border-[#1C1E21]/10 bg-[#F0F2F5] p-6"><b className="text-[#1877F2]">{n}</b><p className="mt-5 font-semibold">{label}</p></div>)}</div></div></section>
    <section className="bg-[#1877F2] py-12 text-white"><div className="section-shell grid gap-6 md:grid-cols-2"><a href="https://www.google.com/maps/search/?api=1&query=House+No+B+129+NIPA+Chorangi+near+Imran+Khan+Cricket+Ground+Block+6+Gulshan-e-Iqbal+Karachi+75300+Pakistan" target="_blank" rel="noopener noreferrer" className="group flex gap-4 rounded-xl p-4 transition hover:bg-white/10"><MapPin className="mt-1 h-6 w-6 shrink-0 transition group-hover:-translate-y-1"/><div><b>Pakistan office</b><p className="mt-1 text-sm text-white/70">House No. B, 129 NIPA Chorangi, near Imran Khan Cricket Ground, Block 6 Gulshan-e-Iqbal, Karachi, 75300, Pakistan</p></div></a><a href="https://www.google.com/maps/search/?api=1&query=8903+Pines+Blvd+217+153+Pembroke+Pines+FL+33024+USA" target="_blank" rel="noopener noreferrer" className="group flex gap-4 rounded-xl p-4 transition hover:bg-white/10"><MapPin className="mt-1 h-6 w-6 shrink-0 transition group-hover:-translate-y-1"/><div><b>USA headquarters</b><p className="mt-1 text-sm text-white/70">8903 Pines Blvd 217 153, Pembroke Pines, FL 33024, USA</p></div></a></div></section>
    <SiteFooter/>
  </main>;
}

function Field({label,name,type="text"}:{label:string;name:string;type?:string}){return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span><input required name={name} type={type} className="h-[50px] w-full rounded-xl border border-[#1C1E21]/12 bg-[#F0F2F5] px-4 outline-none focus:border-[#1877F2]"/></label>}
