"use client";

import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, Building2, ChevronDown, GraduationCap, HeartPulse, Landmark, Lightbulb, Menu, Radio, ShieldCheck, Sparkles, Users, X, Zap } from "lucide-react";
import { useState } from "react";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";

const principles = [
  { label: "Our Vision", icon: Lightbulb, copy: "To revolutionize the digital landscape through creativity, innovation, and steady expertise, crafting experiences that leave a lasting impact." },
  { label: "Our Values", icon: ShieldCheck, copy: "Integrity, excellence, collaboration, and client-centricity guide every decision. We value transparency, teamwork, and exceeding expectations." },
  { label: "Our Mission", icon: Zap, copy: "To empower businesses through technology and creativity, delivering innovative solutions that drive success and shape the digital future." }
];

const industries = ["Governmental Sector", "Telecom & Media", "Professional Services", "Healthcare", "Oil & Gas", "Energy & Utilities", "Education", "Finance & Banking", "Construction", "Manufacturing"];
const industryIcons = [Landmark, Radio, Users, HeartPulse, Building2, Zap, GraduationCap, Landmark, Building2, Building2];

export default function AboutPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <main className="min-h-screen bg-[#F0F2F5] text-[#1C1E21]">
    <SiteHeader/>

    <section className="relative overflow-hidden border-b border-[#1C1E21]/10 bg-white pt-24">
      <div className="absolute inset-0 opacity-40 [background-image:linear-gradient(rgba(24,119,242,.07)_1px,transparent_1px),linear-gradient(90deg,rgba(24,119,242,.07)_1px,transparent_1px)] [background-size:64px_64px]"/>
      <div className="section-shell relative grid min-h-[650px] items-center gap-12 py-14 lg:grid-cols-[1.02fr_.98fr]">
        <motion.div initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.7}}><p className="flex items-center gap-2 text-sm font-semibold uppercase tracking-[.2em] text-[#1877F2]"><Sparkles className="h-4 w-4"/>The story behind Opus Geeks</p><h1 className="mt-6 max-w-3xl text-balance text-5xl font-semibold leading-[1.02] md:text-7xl">Technology powered by <span className="text-[#1877F2]">creative people.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#1C1E21]/60">We are a collective of passionate people driven by technology and creativity. Our journey began with a shared vision to blend innovation with expertise and build digital solutions that inspire and empower.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/#contact" className="inline-flex items-center gap-3 rounded-full bg-[#1877F2] px-6 py-4 font-semibold text-white shadow-[0_14px_35px_rgba(24,119,242,.25)]">Work with us <ArrowRight className="h-5 w-5"/></Link><Link href="/portfolio" className="rounded-full border border-[#1C1E21]/15 bg-white px-6 py-4 font-semibold">Explore our work</Link></div><div className="mt-9 grid max-w-xl grid-cols-3 overflow-hidden rounded-xl border border-[#1C1E21]/10 bg-white shadow-sm">{[["40+","Clients"],["540+","Projects"],["25+","Awards"]].map(([value,label])=><div key={label} className="border-r border-[#1C1E21]/10 p-4 last:border-r-0"><b className="text-xl text-[#1877F2]">{value}</b><span className="mt-1 block text-xs text-[#1C1E21]/45">{label}</span></div>)}</div></motion.div>
        <motion.div initial={{opacity:0,x:35}} animate={{opacity:1,x:0}} transition={{duration:.8}} className="relative mx-auto h-[500px] w-full max-w-[560px]"><div className="absolute inset-8 rounded-full bg-[#1877F2]/10"/><motion.div animate={{y:[0,-9,0],rotate:[-1,1,-1]}} transition={{duration:.8}} className="absolute inset-4"><Image src="/images/about-story.png" alt="Opus Geeks business collaboration" fill priority className="object-contain drop-shadow-[0_30px_45px_rgba(28,30,33,.2)]"/></motion.div><div className="absolute bottom-4 right-0 rounded-xl border border-[#1877F2]/15 bg-white p-4 shadow-xl"><p className="text-xs uppercase tracking-[.18em] text-[#1877F2]">Built together</p><b className="mt-1 block">Strategy · Design · Engineering</b></div></motion.div>
      </div>
    </section>

    <section className="bg-[#F0F2F5] py-20 md:py-28"><div className="section-shell grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#1877F2]">Expertise</p><h2 className="mt-4 text-balance text-4xl font-semibold md:text-6xl">It&apos;s been years in the making.</h2></div><div className="rounded-2xl border border-[#1C1E21]/10 bg-white p-7 shadow-[0_18px_50px_rgba(28,30,33,.07)] md:p-10"><p className="text-lg leading-8 text-[#1C1E21]/65">With collective experience spanning years, our team has sharpened its skills across technology and creativity. From web development and digital marketing to graphic design and artificial intelligence, we stay immersed in an ever-evolving landscape of innovation.</p><div className="mt-8 flex flex-wrap gap-2">{["Product strategy","Web platforms","Mobile apps","UI/UX systems","AI solutions"].map(item=><span key={item} className="rounded-full bg-[#E7F3FF] px-4 py-2 text-sm font-semibold text-[#1877F2]">{item}</span>)}</div></div></div></section>

    <section className="bg-white py-20 md:py-28"><div className="section-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#1877F2]">What guides us</p><h2 className="mt-4 text-balance text-4xl font-semibold md:text-6xl">Clear principles behind every product.</h2></div><div className="mt-12 grid overflow-hidden rounded-2xl border border-[#1C1E21]/10 lg:grid-cols-3">{principles.map((item,index)=>{const Icon=item.icon;return <motion.article initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.1}} key={item.label} className="border-b border-[#1C1E21]/10 p-7 last:border-0 lg:border-b-0 lg:border-r lg:last:border-r-0 md:p-9"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#E7F3FF] text-[#1877F2]"><Icon className="h-6 w-6"/></div><h3 className="mt-7 text-2xl font-semibold">{item.label}</h3><p className="mt-4 leading-7 text-[#1C1E21]/55">{item.copy}</p></motion.article>})}</div></div></section>

    <section className="bg-[#F0F2F5] py-20 md:py-28"><div className="section-shell"><div className="grid gap-8 lg:grid-cols-2 lg:items-end"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#1877F2]">Industries</p><h2 className="mt-4 text-balance text-4xl font-semibold md:text-6xl">Several sectors. One product mindset.</h2></div><p className="text-lg leading-8 text-[#1C1E21]/60">Our solutions are tailored to each industry&apos;s specific needs. By understanding sector challenges and trends, we help organizations move confidently through digital change.</p></div><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{industries.map((industry,index)=>{const Icon=industryIcons[index];return <motion.div whileHover={{y:-5}} key={industry} className="flex min-h-36 flex-col justify-between rounded-xl border border-[#1C1E21]/10 bg-white p-5 shadow-sm"><Icon className="h-6 w-6 text-[#1877F2]"/><p className="mt-6 font-semibold">{industry}</p></motion.div>})}</div></div></section>

    <section className="bg-[#1877F2] py-16 text-white"><div className="section-shell flex flex-col gap-8 md:flex-row md:items-center md:justify-between"><div><p className="text-sm uppercase tracking-[.2em] text-white/65">Shape what comes next</p><h2 className="mt-3 max-w-3xl text-balance text-4xl font-semibold md:text-6xl">Let&apos;s build meaningful technology together.</h2></div><Link href="/#contact" className="inline-flex shrink-0 items-center gap-3 self-start rounded-full bg-white px-6 py-4 font-semibold text-[#1877F2]">Start a conversation <ArrowRight className="h-5 w-5"/></Link></div></section>
    <SiteFooter/>
  </main>;
}

function AboutHeader({menuOpen,setMenuOpen}:{menuOpen:boolean;setMenuOpen:(value:boolean)=>void}){return <header className="fixed inset-x-0 top-0 z-50 border-b border-[#1C1E21]/10 bg-white/95 shadow-sm backdrop-blur-xl"><div className="section-shell flex h-24 items-center justify-between"><Link href="/" className="relative h-16 w-40"><Image src="/images/opus-logo.png" alt="Opus Geeks" fill className="object-contain object-left"/><span className="absolute inset-x-0 bottom-0 text-center text-[11px] tracking-[.24em]">OPUSGEEKS</span></Link><nav className="hidden items-center gap-7 text-sm lg:flex"><Link href="/">Home</Link><div className="group relative"><button className="flex items-center gap-1">Services <ChevronDown className="h-4 w-4"/></button><div className="invisible absolute left-1/2 top-8 w-56 -translate-x-1/2 translate-y-2 rounded-xl border bg-white p-2 opacity-0 shadow-xl transition group-hover:visible group-hover:translate-y-0 group-hover:opacity-100"><Link href="/app-development" className="block rounded-lg px-3 py-2 hover:bg-[#F0F2F5]">App Development</Link><Link href="/web-development" className="block rounded-lg px-3 py-2 hover:bg-[#F0F2F5]">Web Development</Link><Link href="/ux-ui-design" className="block rounded-lg px-3 py-2 hover:bg-[#F0F2F5]">UX/UI Design</Link></div></div><Link href="/portfolio">Portfolio</Link><Link href="/blogs">Blogs</Link><Link href="/about" className="font-semibold text-[#1877F2]">About</Link><Link href="/#contact">Contact Us</Link><Link href="/faqs">FAQs</Link></nav><Link href="/#contact" className="hidden rounded-full bg-[#1C1E21] px-6 py-3 font-semibold text-white lg:block">Get Started</Link><button onClick={()=>setMenuOpen(!menuOpen)} className="flex h-11 w-11 items-center justify-center rounded-full border lg:hidden">{menuOpen?<X/>:<Menu/>}</button></div>{menuOpen?<nav className="section-shell space-y-1 pb-5"><Link className="block rounded-xl px-4 py-3" href="/">Home</Link><Link className="block rounded-xl px-4 py-3" href="/portfolio">Portfolio</Link><Link className="block rounded-xl px-4 py-3" href="/blogs">Blogs</Link><Link className="block rounded-xl bg-[#E7F3FF] px-4 py-3 font-semibold text-[#1877F2]" href="/about">About</Link><Link className="block rounded-xl px-4 py-3" href="/#contact">Contact Us</Link></nav>:null}</header>}
function AboutFooter(){return <footer className="border-t border-[#1C1E21]/10 bg-white py-12"><div className="section-shell flex flex-col gap-7 md:flex-row md:items-center md:justify-between"><div><div className="relative h-16 w-44"><Image src="/images/opus-logo.png" alt="" fill className="object-contain object-left"/></div><p className="mt-3 text-sm text-[#1C1E21]/50">Creativity, technology, and dependable product delivery.</p></div><div className="flex flex-wrap gap-5 text-sm text-[#1C1E21]/55"><Link href="/portfolio">Portfolio</Link><Link href="/blogs">Blogs</Link><Link href="/app-development">Services</Link><a href="mailto:contact@opusgeeks.com">contact@opusgeeks.com</a></div></div></footer>}
