"use client";

import Link from "next/link";
import { motion, useScroll, useSpring } from "framer-motion";
import { ArrowRight, BookOpen, Check, FileText, Scale, ShieldCheck } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";

const sections = [
  { title: "License to Use Website", icon: FileText, body: "Unless otherwise stated, Opus Geeks and/or its licensors own the intellectual property rights in the website and material on the website. Subject to the license below, all these intellectual property rights are reserved. You may view, download for caching purposes only, and print pages from the website for your own personal use, subject to the restrictions set out below and elsewhere in these terms and conditions." },
  { title: "Acceptable Use", icon: ShieldCheck, body: "You must not use our website in any way that causes, or may cause, damage to the website or impairment of its availability or accessibility; or in any way that is unlawful, illegal, fraudulent, or harmful, or in connection with any unlawful, illegal, fraudulent, or harmful purpose or activity. You must not use our website to copy, store, host, transmit, send, publish, or distribute material which consists of, or is linked to, spyware, a computer virus, Trojan horse, worm, keystroke logger, rootkit, or other malicious software." },
  { title: "Restricted Access", icon: ShieldCheck, body: "Access to certain areas of our website is restricted. Opus Geeks reserves the right to restrict access to areas of our website, or indeed our whole website, at Opus Geeks' discretion." },
  { title: "User Content", icon: BookOpen, body: "In these terms and conditions, ‘your user content’ means material, including without limitation text, images, audio material, video material, and audio-visual material, that you submit to our website for any purpose. You grant Opus Geeks a worldwide, irrevocable, non-exclusive, royalty-free license to use, reproduce, adapt, publish, translate, and distribute your user content in any existing or future media. You also grant Opus Geeks the right to sublicense these rights and bring an action for infringement of these rights." },
  { title: "Limitations of Liability", icon: Scale, body: "Opus Geeks will not be liable to you, whether under the law of contract, the law of torts, or otherwise, in relation to the contents or use of this website: to the extent that the website is provided free of charge, for any direct loss; for any indirect, special, or consequential loss; or for business losses, loss of revenue, income, profits, anticipated savings, contracts, business relationships, reputation, goodwill, information, or data." },
  { title: "Variation", icon: FileText, body: "Opus Geeks may revise these terms and conditions from time to time. Revised terms and conditions will apply to the use of our website from the date they are published on our website." },
  { title: "Entire Agreement", icon: Check, body: "These terms and conditions, together with Opus Geeks' Privacy Policy, constitute the entire agreement between you and Opus Geeks in relation to your use of our website and supersede all previous agreements concerning its use." },
  { title: "Law and Jurisdiction", icon: Scale, body: "These terms and conditions will be governed by and construed in accordance with the laws of Pakistan. Any disputes relating to these terms and conditions will be subject to the exclusive jurisdiction of the courts of Pakistan. By using Opus Geeks' website, you agree to abide by these terms and conditions. If you do not agree with any part of them, you must not use the website." }
];

export default function TermsPage(){
  const {scrollYProgress}=useScroll(); const progress=useSpring(scrollYProgress,{stiffness:110,damping:28,mass:.25});
  return <main className="min-h-screen bg-[#F0F2F5] text-[#1C1E21]"><motion.div style={{scaleX:progress}} className="fixed inset-x-0 top-0 z-[70] h-[3px] origin-left bg-[#1877F2]"/><SiteHeader/>
    <section className="relative overflow-hidden border-b border-[#1C1E21]/10 bg-white pt-24"><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(rgba(24,119,242,.07)_1px,transparent_1px),linear-gradient(90deg,rgba(24,119,242,.07)_1px,transparent_1px)] [background-size:64px_64px]"/><div className="section-shell relative grid min-h-[430px] items-center gap-10 py-16 lg:grid-cols-[1fr_.65fr]"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}}><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#1877F2]">Legal information</p><h1 className="mt-5 text-balance text-5xl font-semibold leading-[1.02] md:text-7xl">Terms &amp; <span className="text-[#1877F2]">Conditions.</span></h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#1C1E21]/60">These terms govern your use of the Opus Geeks website. By using our website, you accept these terms in full. If you disagree with any part of them, you must not use the website.</p></motion.div><motion.div initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} className="mx-auto flex h-48 w-48 items-center justify-center rounded-full border-[18px] border-[#E7F3FF] bg-[#1877F2] text-white shadow-[0_24px_55px_rgba(24,119,242,.25)]"><Scale className="h-20 w-20"/></motion.div></div></section>

    <section className="py-20 md:py-28"><div className="section-shell grid gap-10 lg:grid-cols-[280px_1fr]"><aside className="lg:sticky lg:top-32 lg:self-start"><div className="rounded-2xl border border-[#1C1E21]/10 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#1877F2]">On this page</p><nav className="mt-4 space-y-1">{sections.map((section,index)=><a key={section.title} href={`#term-${index+1}`} className="flex gap-3 rounded-lg px-3 py-2.5 text-sm text-[#1C1E21]/55 transition hover:bg-[#E7F3FF] hover:text-[#1877F2]"><span className="font-semibold text-[#1877F2]">{String(index+1).padStart(2,"0")}</span>{section.title}</a>)}</nav></div><div className="mt-4 rounded-2xl bg-[#1877F2] p-5 text-white"><p className="text-sm text-white/70">Questions about these terms?</p><Link href="/contact-us" className="mt-4 inline-flex items-center gap-2 font-semibold">Contact our team <ArrowRight className="h-4 w-4"/></Link></div></aside>
      <div className="space-y-4">{sections.map((section,index)=>{const Icon=section.icon;return <motion.article id={`term-${index+1}`} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-60px"}} key={section.title} className="scroll-mt-32 rounded-2xl border border-[#1C1E21]/10 bg-white p-6 shadow-sm md:p-9"><div className="flex items-start gap-5"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-[#E7F3FF] text-[#1877F2]"><Icon className="h-6 w-6"/></span><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#1877F2]">Section {String(index+1).padStart(2,"0")}</p><h2 className="mt-2 text-2xl font-semibold md:text-3xl">{section.title}</h2></div></div><p className="mt-6 leading-8 text-[#1C1E21]/62">{section.body}</p></motion.article>})}</div></div></section>
    <section className="bg-[#1877F2] py-14 text-white"><div className="section-shell flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div><p className="text-sm uppercase tracking-[.2em] text-white/65">Need clarification?</p><h2 className="mt-3 text-3xl font-semibold md:text-4xl">We&apos;re here to answer your questions.</h2></div><Link href="/contact-us" className="inline-flex items-center gap-3 self-start rounded-full bg-white px-6 py-4 font-semibold text-[#1877F2]">Get in touch <ArrowRight className="h-5 w-5"/></Link></div></section><SiteFooter/>
  </main>;
}
