"use client";

import Link from "next/link";
import { motion, useScroll, useSpring } from "framer-motion";
import { ArrowRight, Baby, Cookie, Database, ExternalLink, Mail, RefreshCw, ShieldCheck } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";

const sections = [
  { title: "Information We Collect", icon: Database, body: "We may collect personal information such as your name, email address, phone number, and company name when you voluntarily submit it through our website contact forms or communicate with us by email or other means." },
  { title: "How We Use Your Information", icon: ShieldCheck, body: "We use collected information to communicate with you, respond to inquiries, provide services, improve our website, and send relevant updates and promotional materials related to Opus Geeks' products and services. We do not sell, rent, or share your personal information with third parties for marketing purposes without your explicit consent." },
  { title: "Cookies", icon: Cookie, body: "Our website may use cookies to enhance your browsing experience. Cookies are small files stored on your device that help us recognize preferences and understand usage patterns. You can disable cookies through your browser settings, although this may affect access to certain website features." },
  { title: "Third-Party Links", icon: ExternalLink, body: "Our website may contain links to third-party websites or services that are not owned or controlled by Opus Geeks. We are not responsible for the privacy practices or content of those sites. We encourage you to review their privacy policies when visiting them." },
  { title: "Data Security", icon: ShieldCheck, body: "We take appropriate measures to protect personal information from unauthorized access, alteration, disclosure, or destruction. However, no internet transmission or electronic storage method is completely secure, and we cannot guarantee absolute security." },
  { title: "Children's Privacy", icon: Baby, body: "Our website is not intended for children under the age of 13. We do not knowingly collect personal information from children under 13. If you believe information was inadvertently collected from a child under 13, contact us immediately so we can take steps to delete it." },
  { title: "Changes to This Privacy Policy", icon: RefreshCw, body: "We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. Material changes will be communicated by posting the updated Privacy Policy on this page." },
  { title: "Contact Us", icon: Mail, body: "If you have questions or concerns about this Privacy Policy or our data practices, contact us at contact@opusgeeks.com. By using our website, you consent to this Privacy Policy. If you do not agree with its terms, please do not use our website." }
];

export default function PrivacyPolicyPage(){
  const {scrollYProgress}=useScroll(); const progress=useSpring(scrollYProgress,{stiffness:110,damping:28,mass:.25});
  return <main className="min-h-screen bg-[#F0F2F5] text-[#1C1E21]"><motion.div style={{scaleX:progress}} className="fixed inset-x-0 top-0 z-[70] h-[3px] origin-left bg-[#1877F2]"/><SiteHeader/>
    <section className="relative overflow-hidden border-b border-[#1C1E21]/10 bg-white pt-24"><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(rgba(24,119,242,.07)_1px,transparent_1px),linear-gradient(90deg,rgba(24,119,242,.07)_1px,transparent_1px)] [background-size:64px_64px]"/><div className="section-shell relative grid min-h-[430px] items-center gap-10 py-16 lg:grid-cols-[1fr_.65fr]"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}}><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#1877F2]">Your information, handled responsibly</p><h1 className="mt-5 text-balance text-5xl font-semibold leading-[1.02] md:text-7xl">Privacy <span className="text-[#1877F2]">Policy.</span></h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#1C1E21]/60">Opus Geeks is committed to protecting the privacy and security of website visitors and users. This policy explains how we collect, use, and safeguard personal information when you visit our website or interact with us.</p></motion.div><motion.div initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} className="mx-auto flex h-48 w-48 items-center justify-center rounded-full border-[18px] border-[#E7F3FF] bg-[#1877F2] text-white shadow-[0_24px_55px_rgba(24,119,242,.25)]"><ShieldCheck className="h-20 w-20"/></motion.div></div></section>

    <section className="py-20 md:py-28"><div className="section-shell grid gap-10 lg:grid-cols-[280px_1fr]"><aside className="lg:sticky lg:top-32 lg:self-start"><div className="rounded-2xl border border-[#1C1E21]/10 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#1877F2]">On this page</p><nav className="mt-4 space-y-1">{sections.map((section,index)=><a key={section.title} href={`#term-${index+1}`} className="flex gap-3 rounded-lg px-3 py-2.5 text-sm text-[#1C1E21]/55 transition hover:bg-[#E7F3FF] hover:text-[#1877F2]"><span className="font-semibold text-[#1877F2]">{String(index+1).padStart(2,"0")}</span>{section.title}</a>)}</nav></div><div className="mt-4 rounded-2xl bg-[#1877F2] p-5 text-white"><p className="text-sm text-white/70">Questions about your privacy?</p><Link href="/contact-us" className="mt-4 inline-flex items-center gap-2 font-semibold">Contact our team <ArrowRight className="h-4 w-4"/></Link></div></aside>
      <div className="space-y-4">{sections.map((section,index)=>{const Icon=section.icon;return <motion.article id={`term-${index+1}`} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-60px"}} key={section.title} className="scroll-mt-32 rounded-2xl border border-[#1C1E21]/10 bg-white p-6 shadow-sm md:p-9"><div className="flex items-start gap-5"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-[#E7F3FF] text-[#1877F2]"><Icon className="h-6 w-6"/></span><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#1877F2]">Section {String(index+1).padStart(2,"0")}</p><h2 className="mt-2 text-2xl font-semibold md:text-3xl">{section.title}</h2></div></div><p className="mt-6 leading-8 text-[#1C1E21]/62">{section.body}</p></motion.article>})}</div></div></section>
    <section className="bg-[#1877F2] py-14 text-white"><div className="section-shell flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div><p className="text-sm uppercase tracking-[.2em] text-white/65">Need clarification?</p><h2 className="mt-3 text-3xl font-semibold md:text-4xl">We&apos;re here to answer your questions.</h2></div><Link href="/contact-us" className="inline-flex items-center gap-3 self-start rounded-full bg-white px-6 py-4 font-semibold text-[#1877F2]">Get in touch <ArrowRight className="h-5 w-5"/></Link></div></section><SiteFooter/>
  </main>;
}
