"use client";

import Image from "next/image";
import Link from "next/link";
import { AnimatePresence, motion, useScroll, useSpring } from "framer-motion";
import { ArrowRight, ArrowUpRight, CalendarDays, ChevronDown, Clock3, Menu, Search, Sparkles, X } from "lucide-react";
import { useMemo, useState } from "react";

const articles = [
  { title: "How to plan a mobile app that users keep", category: "App Development", time: "7 min", excerpt: "A practical framework for turning a product idea into a focused roadmap, useful feature set, and confident launch.", color: "#E7F3FF" },
  { title: "Core Web Vitals: speed that supports growth", category: "Web Development", time: "6 min", excerpt: "Why performance affects conversion, visibility, and trust, plus the improvements that create the biggest impact.", color: "#E9F8E5" },
  { title: "Design systems that scale beyond one screen", category: "UI/UX Design", time: "8 min", excerpt: "Build consistent digital products faster with reusable components, accessible patterns, and shared design decisions.", color: "#FFF3D6" },
  { title: "Choosing between native and cross-platform apps", category: "App Development", time: "9 min", excerpt: "Compare performance, cost, timelines, and maintenance before selecting the right mobile technology approach.", color: "#F1EAFE" },
  { title: "From visitor to customer: better website journeys", category: "Web Development", time: "5 min", excerpt: "Use clearer hierarchy, stronger proof, and intentional calls to action to remove friction from the buying journey.", color: "#FFECE8" },
  { title: "UX research without slowing down delivery", category: "UI/UX Design", time: "6 min", excerpt: "Lean research methods that help teams validate assumptions and make better product decisions before development.", color: "#E5F7F5" }
];
const categories = ["All", "App Development", "Web Development", "UI/UX Design"];

export default function BlogsPage() {
  const [active, setActive] = useState("All");
  const [query, setQuery] = useState("");
  const [menuOpen, setMenuOpen] = useState(false);
  const { scrollYProgress } = useScroll();
  const progress = useSpring(scrollYProgress, { stiffness: 110, damping: 28, mass: .25 });
  const visible = useMemo(() => articles.filter((article) => (active === "All" || article.category === active) && article.title.toLowerCase().includes(query.toLowerCase())), [active, query]);

  return <main className="min-h-screen bg-[#F0F2F5] text-[#1C1E21]">
    <motion.div style={{scaleX:progress}} className="fixed inset-x-0 top-0 z-[70] h-[3px] origin-left bg-[#1877F2]"/>
    <BlogsHeader menuOpen={menuOpen} setMenuOpen={setMenuOpen}/>

    <section className="relative overflow-hidden border-b border-[#1C1E21]/10 bg-white pt-24">
      <div className="absolute inset-0 opacity-40 [background-image:linear-gradient(rgba(24,119,242,.07)_1px,transparent_1px),linear-gradient(90deg,rgba(24,119,242,.07)_1px,transparent_1px)] [background-size:64px_64px]"/>
      <div className="section-shell relative grid min-h-[610px] items-center gap-10 py-14 lg:grid-cols-[1.05fr_.95fr]">
        <motion.div initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.7}}><p className="flex items-center gap-2 text-sm font-semibold uppercase tracking-[.2em] text-[#1877F2]"><Sparkles className="h-4 w-4"/>Ideas for better digital products</p><h1 className="mt-6 text-balance text-5xl font-semibold leading-[1.02] md:text-7xl">Insights &amp; <span className="text-[#1877F2]">inspiration.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#1C1E21]/60">Explore thoughtful ideas, practical guidance, and creative perspectives designed to help teams build stronger products and make confident technology decisions.</p><a href="#articles" className="mt-9 inline-flex items-center gap-3 rounded-full bg-[#1877F2] px-6 py-4 font-semibold text-white shadow-[0_14px_35px_rgba(24,119,242,.25)]">Explore articles <ArrowRight className="h-5 w-5"/></a></motion.div>
        <motion.div initial={{opacity:0,x:36}} animate={{opacity:1,x:0}} transition={{duration:.8}} className="relative mx-auto h-[470px] w-full max-w-[530px]"><div className="absolute inset-10 rounded-full bg-[#1877F2]/10"/><motion.div animate={{y:[0,-10,0],rotate:[-2,1,-2]}} transition={{duration:7,repeat:Infinity}} className="absolute inset-y-0 left-1/2 w-[355px] max-w-[78%] -translate-x-1/2 overflow-hidden rounded-2xl border-4 border-white bg-[#1877F2] shadow-2xl"><Image src="/images/blog-hero.png" alt="Opus Geeks insights and inspiration" fill priority className="object-cover"/></motion.div><div className="absolute bottom-6 left-3 rounded-xl border border-[#1877F2]/15 bg-white p-4 shadow-xl"><p className="text-xs uppercase tracking-[.18em] text-[#1877F2]">Fresh thinking</p><b className="mt-1 block">Product · Design · Engineering</b></div></motion.div>
      </div>
    </section>

    <section className="bg-[#F0F2F5] py-16 md:py-24"><div className="section-shell"><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#1877F2]">Featured perspective</p><div className="mt-6 grid overflow-hidden rounded-2xl border border-[#1C1E21]/10 bg-white shadow-[0_18px_55px_rgba(28,30,33,.08)] lg:grid-cols-2"><div className="relative min-h-[330px]"><Image src="/images/blog-feature.png" alt="Product team exploring digital strategy" fill className="object-cover"/></div><div className="flex flex-col justify-center p-7 md:p-12"><span className="text-sm font-semibold text-[#1877F2]">Product Strategy</span><h2 className="mt-4 text-balance text-3xl font-semibold md:text-5xl">Unveiling perspectives: insight that moves products forward.</h2><p className="mt-5 leading-7 text-[#1C1E21]/60">Look beyond conventional wisdom, examine real customer needs, and discover the strategic choices that turn ambitious ideas into valuable digital experiences.</p><div className="mt-7 flex items-center gap-5 text-sm text-[#1C1E21]/45"><span className="flex items-center gap-2"><CalendarDays className="h-4 w-4"/>Editorial team</span><span className="flex items-center gap-2"><Clock3 className="h-4 w-4"/>8 min read</span></div></div></div></div></section>

    <section id="articles" className="scroll-mt-28 bg-white py-20 md:py-28"><div className="section-shell"><div className="flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#1877F2]">Knowledge library</p><h2 className="mt-4 text-4xl font-semibold md:text-6xl">Featured articles.</h2></div><label className="flex w-full max-w-sm items-center gap-3 rounded-full border border-[#1C1E21]/10 bg-[#F0F2F5] px-4 py-3"><Search className="h-5 w-5 text-[#1C1E21]/35"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search articles" className="w-full bg-transparent text-sm outline-none"/></label></div><div className="mt-8 flex gap-2 overflow-x-auto pb-2">{categories.map((category)=><button key={category} onClick={()=>setActive(category)} className={`whitespace-nowrap rounded-full px-4 py-2.5 text-sm font-semibold transition ${active===category?'bg-[#1877F2] text-white':'border border-[#1C1E21]/10 bg-[#F0F2F5] text-[#1C1E21]/55'}`}>{category}</button>)}</div>
      <motion.div layout className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><AnimatePresence mode="popLayout">{visible.map((article,index)=><motion.article layout initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,scale:.96}} transition={{duration:.35,delay:index*.04}} key={article.title} className="group overflow-hidden rounded-2xl border border-[#1C1E21]/10 bg-white shadow-[0_12px_35px_rgba(28,30,33,.06)]"><div className="relative h-44 overflow-hidden p-5" style={{backgroundColor:article.color}}><div className="absolute -right-10 -top-10 h-36 w-36 rounded-full border-[28px] border-white/50"/><span className="relative rounded-full bg-white/80 px-3 py-1.5 text-xs font-semibold text-[#1877F2]">{article.category}</span><div className="absolute bottom-5 left-5 right-5 flex gap-2">{[70,45,82].map((width,i)=><i key={i} className="h-2 rounded-full bg-[#1877F2]/25" style={{width:`${width}%`}}/>)}</div></div><div className="p-6"><div className="flex items-center justify-between text-xs text-[#1C1E21]/40"><span>Opus Geeks Editorial</span><span>{article.time} read</span></div><h3 className="mt-4 text-2xl font-semibold leading-8">{article.title}</h3><p className="mt-4 text-sm leading-6 text-[#1C1E21]/55">{article.excerpt}</p><button className="mt-6 flex items-center gap-2 text-sm font-semibold text-[#1877F2]">Read insight <ArrowUpRight className="h-4 w-4 transition group-hover:translate-x-1 group-hover:-translate-y-1"/></button></div></motion.article>)}</AnimatePresence></motion.div>{visible.length===0?<p className="mt-12 text-center text-[#1C1E21]/50">No articles match your search.</p>:null}</div></section>

    <section className="bg-[#1877F2] py-16 text-white"><div className="section-shell flex flex-col gap-7 md:flex-row md:items-center md:justify-between"><div><p className="text-sm uppercase tracking-[.2em] text-white/65">Build with clarity</p><h2 className="mt-3 text-4xl font-semibold md:text-5xl">Turn insight into your next product.</h2></div><Link href="/#contact" className="inline-flex items-center gap-3 self-start rounded-full bg-white px-6 py-4 font-semibold text-[#1877F2]">Talk to our team <ArrowRight className="h-5 w-5"/></Link></div></section>
    <BlogsFooter/>
  </main>;
}

function BlogsHeader({menuOpen,setMenuOpen}:{menuOpen:boolean;setMenuOpen:(value:boolean)=>void}){return <header className="fixed inset-x-0 top-0 z-50 border-b border-[#1C1E21]/10 bg-white/95 shadow-sm backdrop-blur-xl"><div className="section-shell flex h-24 items-center justify-between"><Link href="/" className="relative h-16 w-40"><Image src="/images/opus-logo.png" alt="Opus Geeks" fill className="object-contain object-left"/><span className="absolute inset-x-0 bottom-0 text-center text-[11px] tracking-[.24em]">OPUSGEEKS</span></Link><nav className="hidden items-center gap-7 text-sm lg:flex"><Link href="/">Home</Link><div className="group relative"><button className="flex items-center gap-1">Services <ChevronDown className="h-4 w-4"/></button><div className="invisible absolute left-1/2 top-8 w-56 -translate-x-1/2 translate-y-2 rounded-xl border bg-white p-2 opacity-0 shadow-xl transition group-hover:visible group-hover:translate-y-0 group-hover:opacity-100"><Link href="/app-development" className="block rounded-lg px-3 py-2 hover:bg-[#F0F2F5]">App Development</Link><Link href="/web-development" className="block rounded-lg px-3 py-2 hover:bg-[#F0F2F5]">Web Development</Link><Link href="/ux-ui-design" className="block rounded-lg px-3 py-2 hover:bg-[#F0F2F5]">UX/UI Design</Link></div></div><Link href="/portfolio">Portfolio</Link><Link href="/blogs" className="font-semibold text-[#1877F2]">Blogs</Link><Link href="/about">About</Link><Link href="/#contact">Contact Us</Link><Link href="/#faqs">FAQs</Link></nav><Link href="/#contact" className="hidden rounded-full bg-[#1C1E21] px-6 py-3 font-semibold text-white lg:block">Get Started</Link><button onClick={()=>setMenuOpen(!menuOpen)} className="flex h-11 w-11 items-center justify-center rounded-full border lg:hidden">{menuOpen?<X/>:<Menu/>}</button></div>{menuOpen?<nav className="section-shell space-y-1 pb-5"><Link className="block rounded-xl px-4 py-3" href="/">Home</Link><Link className="block rounded-xl px-4 py-3" href="/portfolio">Portfolio</Link><Link className="block rounded-xl bg-[#E7F3FF] px-4 py-3 font-semibold text-[#1877F2]" href="/blogs">Blogs</Link><Link className="block rounded-xl px-4 py-3" href="/about">About</Link><Link className="block rounded-xl px-4 py-3" href="/#contact">Contact Us</Link></nav>:null}</header>}
function BlogsFooter(){return <footer className="border-t border-[#1C1E21]/10 bg-white py-12"><div className="section-shell flex flex-col gap-7 md:flex-row md:items-center md:justify-between"><div><div className="relative h-16 w-44"><Image src="/images/opus-logo.png" alt="" fill className="object-contain object-left"/></div><p className="mt-3 text-sm text-[#1C1E21]/50">Ideas for better products, stronger brands, and smarter growth.</p></div><div className="flex flex-wrap gap-5 text-sm text-[#1C1E21]/55"><Link href="/portfolio">Portfolio</Link><Link href="/app-development">App Development</Link><Link href="/web-development">Web Development</Link><a href="mailto:contact@opusgeeks.com">contact@opusgeeks.com</a></div></div></footer>}
