"use client";

import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, ArrowUpRight, CalendarDays, ChevronDown, Clock3, Component, Gauge, Menu, Route, Search, Smartphone, X } from "lucide-react";
import { useMemo, useState } from "react";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";

const articles = [
  { title: "How to plan a mobile app that users keep", category: "App Development", time: "7 min", excerpt: "A practical framework for turning a product idea into a focused roadmap, useful feature set, and confident launch.", color: "#E7F3FF" },
  { title: "Core Web Vitals: speed that supports growth", category: "Web Development", time: "6 min", excerpt: "Why performance affects conversion, visibility, and trust, plus the improvements that create the biggest impact.", color: "#E7F3FF" },
  { title: "Design systems that scale beyond one screen", category: "UI/UX Design", time: "8 min", excerpt: "Build consistent digital products faster with reusable components, accessible patterns, and shared design decisions.", color: "#FFF3D6" },
  { title: "Choosing between native and cross-platform apps", category: "App Development", time: "9 min", excerpt: "Compare performance, cost, timelines, and maintenance before selecting the right mobile technology approach.", color: "#F1EAFE" },
  { title: "From visitor to customer: better website journeys", category: "Web Development", time: "5 min", excerpt: "Use clearer hierarchy, stronger proof, and intentional calls to action to remove friction from the buying journey.", color: "#FFECE8" },
  { title: "UX research without slowing down delivery", category: "UI/UX Design", time: "6 min", excerpt: "Lean research methods that help teams validate assumptions and make better product decisions before development.", color: "#E5F7F5" }
];
const categories = ["All", "App Development", "Web Development", "UI/UX Design"];

export default function BlogsPage() {
  const [active, setActive] = useState("All");
  const [query, setQuery] = useState("");
  const [menuOpen, setMenuOpen] = useState(false);
  const visible = useMemo(() => articles.filter((article) => (active === "All" || article.category === active) && article.title.toLowerCase().includes(query.toLowerCase())), [active, query]);

  return <main className="min-h-screen bg-[#F0F2F5] text-[#1C1E21]">
    <SiteHeader/>

    <section className="relative min-h-[680px] overflow-hidden border-b border-[#1C1E21]/10 bg-white pt-24">
      <Image src="/images/blog-hero-editorial-hd.png" alt="Product design studio with interface systems, research notes, and engineering artifacts" fill priority sizes="100vw" className="object-cover object-[62%_center]"/>
      <div className="absolute inset-y-24 left-0 w-full bg-white/[.88] md:w-[62%] lg:w-[55%]"/>
      <div className="section-shell relative flex min-h-[584px] flex-col justify-between py-12 md:py-16">
        <motion.div initial={false} animate={{opacity:1,y:0}} className="max-w-3xl">
          <div className="flex items-center gap-4"><span className="h-px w-10 bg-[#1877F2]"/><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#1877F2]">Opus Geeks / Journal 01</p></div>
          <h1 className="mt-7 max-w-2xl text-balance text-5xl font-semibold leading-[.98] md:text-7xl">Thinking that helps digital products <span className="font-display font-normal italic text-[#1877F2]">move forward.</span></h1>
          <p className="mt-7 max-w-xl text-base leading-7 text-[#1C1E21]/62 md:text-lg md:leading-8">Practical perspectives on product strategy, interface design, engineering quality, and the decisions connecting them.</p>
          <a href="#articles" className="group mt-8 inline-flex min-h-14 items-center gap-8 bg-[#1C1E21] px-6 font-semibold text-white transition hover:bg-[#1877F2]">Read the journal <ArrowRight className="h-5 w-5 transition-transform group-hover:translate-x-1"/></a>
        </motion.div>
        <div className="mt-12 grid max-w-3xl border-y border-[#1C1E21]/14 bg-white/[.78] sm:grid-cols-[1.2fr_1fr_1fr]">
          <div className="border-b border-[#1C1E21]/12 p-4 sm:border-b-0 sm:border-r"><span className="text-[9px] font-semibold uppercase tracking-[.18em] text-[#1877F2]">Current issue</span><strong className="mt-2 block text-sm">Building with better judgment</strong></div>
          <div className="border-b border-[#1C1E21]/12 p-4 sm:border-b-0 sm:border-r"><span className="text-[9px] font-semibold uppercase tracking-[.18em] text-[#1C1E21]/38">Disciplines</span><strong className="mt-2 block text-sm">Product · Design · Code</strong></div>
          <div className="p-4"><span className="text-[9px] font-semibold uppercase tracking-[.18em] text-[#1C1E21]/38">Reading desk</span><strong className="mt-2 block text-sm">06 field notes</strong></div>
        </div>
      </div>
    </section>

    <section className="relative overflow-hidden bg-[#1C1E21] text-white">
      <div className="section-shell grid lg:grid-cols-[.78fr_1.22fr]">
        <div className="relative flex min-h-[500px] flex-col justify-between border-b border-white/15 py-14 lg:min-h-[620px] lg:border-b-0 lg:border-r lg:py-16 lg:pr-14">
          <span className="pointer-events-none absolute -right-4 top-6 font-display text-[13rem] leading-none text-white/[.035] md:text-[18rem]">01</span>
          <div className="relative"><div className="flex items-center gap-4"><span className="h-px w-10 bg-[#1877F2]"/><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#78B7FF]">Featured perspective / 01</p></div><h2 className="mt-8 max-w-xl text-balance text-4xl font-semibold leading-[1.02] md:text-6xl">Good products begin with <span className="font-display font-normal italic text-[#78B7FF]">better questions.</span></h2><p className="mt-7 max-w-lg text-base leading-7 text-white/58">Look beyond assumptions, examine real customer needs, and make the strategic choices that turn ambitious ideas into useful digital experiences.</p></div>
          <div className="relative mt-10"><div className="flex flex-wrap gap-x-6 gap-y-3 border-t border-white/15 pt-5 text-xs text-white/48"><span className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-[#78B7FF]"/>Opus Editorial</span><span className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-[#78B7FF]"/>8 min read</span><span>Product Strategy</span></div><button className="group mt-7 inline-flex min-h-14 items-center gap-10 bg-[#1877F2] px-6 font-semibold text-white">Read perspective <ArrowUpRight className="h-5 w-5 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></button></div>
        </div>
        <div className="relative min-h-[430px] overflow-hidden lg:min-h-[620px]"><Image src="/images/blog-feature.png" alt="Product strategist exploring an augmented digital interface" fill sizes="(max-width: 1024px) 100vw, 60vw" className="object-cover"/><div className="absolute left-0 top-0 hidden h-full w-20 bg-[#1877F2] lg:block"/><div className="absolute bottom-0 left-0 right-0 grid bg-[#1877F2] sm:grid-cols-3 lg:left-20"><div className="border-b border-white/20 p-5 sm:border-b-0 sm:border-r"><span className="text-[9px] uppercase tracking-[.18em] text-white/55">Signal 01</span><strong className="mt-2 block text-sm">Customer evidence</strong></div><div className="border-b border-white/20 p-5 sm:border-b-0 sm:border-r"><span className="text-[9px] uppercase tracking-[.18em] text-white/55">Signal 02</span><strong className="mt-2 block text-sm">Product judgment</strong></div><div className="p-5"><span className="text-[9px] uppercase tracking-[.18em] text-white/55">Signal 03</span><strong className="mt-2 block text-sm">Measured learning</strong></div></div></div>
      </div>
    </section>

    <section id="articles" className="scroll-mt-28 bg-white py-20 md:py-28"><div className="section-shell"><div className="grid gap-8 border-b border-[#1C1E21]/15 pb-9 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><div className="flex items-center gap-4"><span className="h-px w-10 bg-[#1877F2]"/><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#1877F2]">Knowledge library / 01-06</p></div><h2 className="mt-5 text-balance text-4xl font-semibold md:text-6xl">Ideas made useful.</h2></div><label className="flex min-h-14 w-full items-center gap-3 border-b border-[#1C1E21]/25 px-1 lg:max-w-md lg:justify-self-end"><Search className="h-5 w-5 text-[#1877F2]"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search the journal" className="w-full bg-transparent text-sm outline-none"/></label></div><div className="flex gap-px overflow-x-auto border-b border-[#1C1E21]/15 bg-[#1C1E21]/10" role="tablist">{categories.map((category)=><button key={category} onClick={()=>setActive(category)} className={`min-h-12 whitespace-nowrap px-5 text-xs font-semibold transition ${active===category?'bg-[#1877F2] text-white':'bg-white text-[#1C1E21]/55 hover:text-[#1877F2]'}`}>{category}</button>)}</div>
      <motion.div layout className="mt-8 grid gap-4 md:grid-cols-2">{visible.map((article,index)=><motion.article layout initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.3,delay:index*.035}} key={article.title} className={`group overflow-hidden border border-[#1C1E21]/12 bg-white shadow-[0_18px_45px_rgba(28,30,33,.06)] ${index===0?'md:col-span-2 lg:grid lg:grid-cols-[1.05fr_.95fr]':''}`}><ArticleCover category={article.category} index={index}/><div className={`flex flex-col p-6 md:p-8 ${index===0?'lg:min-h-[360px] lg:justify-center lg:p-12':''}`}><div className="flex items-center justify-between gap-4"><span className="text-[10px] font-semibold uppercase tracking-[.17em] text-[#1877F2]">{article.category}</span><span className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.14em] text-[#1C1E21]/38"><Clock3 className="h-3.5 w-3.5"/>{article.time} read</span></div><h3 className={`mt-5 text-balance font-semibold leading-tight ${index===0?'text-3xl md:text-5xl':'text-2xl md:text-3xl'}`}>{article.title}</h3><p className="mt-5 text-sm leading-6 text-[#1C1E21]/54 md:text-base md:leading-7">{article.excerpt}</p><button className="mt-7 flex items-center justify-between border-t border-[#1C1E21]/12 pt-5 text-sm font-semibold"><span>Read field note</span><span className="grid h-10 w-10 place-items-center bg-[#1C1E21] text-white transition group-hover:bg-[#1877F2]"><ArrowUpRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5"/></span></button></div></motion.article>)}</motion.div>{visible.length===0?<p className="border-b border-[#1C1E21]/15 py-16 text-center text-[#1C1E21]/50">No articles match your search.</p>:null}</div></section>

    <section className="bg-[#1877F2] py-16 text-white"><div className="section-shell flex flex-col gap-7 md:flex-row md:items-center md:justify-between"><div><p className="text-sm uppercase tracking-[.2em] text-white/65">Build with clarity</p><h2 className="mt-3 text-4xl font-semibold md:text-5xl">Turn insight into your next product.</h2></div><Link href="/#contact" className="inline-flex items-center gap-3 self-start rounded-full bg-white px-6 py-4 font-semibold text-[#1877F2]">Talk to our team <ArrowRight className="h-5 w-5"/></Link></div></section>
    <SiteFooter/>
  </main>;
}

function ArticleCover({category,index}:{category:string;index:number}) {
  const Icon = category === "App Development" ? Smartphone : category === "Web Development" ? Gauge : Component;
  return <div className={`relative min-h-[250px] overflow-hidden p-6 ${index===0?'bg-[#1C1E21] text-white md:min-h-[360px]':'bg-[#F0F2F5] text-[#1C1E21]'}`}>
    <div className="absolute inset-0 opacity-35 [background-image:linear-gradient(rgba(255,255,255,.12)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.12)_1px,transparent_1px)] [background-size:44px_44px]"/>
    <div className="relative flex items-start justify-between"><span className={`grid h-12 w-12 place-items-center ${index===0?'bg-[#1877F2] text-white':'border border-[#1877F2]/25 bg-white text-[#1877F2]'}`}><Icon className="h-5 w-5"/></span><span className={`font-display text-5xl leading-none ${index===0?'text-white/16':'text-[#1C1E21]/12'}`}>{String(index+1).padStart(2,"0")}</span></div>
    {category === "App Development" ? <div className="relative mx-auto mt-7 flex max-w-[310px] items-end justify-center gap-3"><div className={`h-28 w-16 border p-2 ${index===0?'border-white/25 bg-white/10':'border-[#1C1E21]/12 bg-white'}`}><div className="h-2 w-7 bg-[#1877F2]"/><div className={`mt-3 h-12 ${index===0?'bg-white/10':'bg-[#E7F3FF]'}`}/><div className="mt-3 grid grid-cols-3 gap-1">{[1,2,3].map(item=><i key={item} className="h-3 bg-[#1877F2]/45"/>)}</div></div><Route className="mb-12 h-12 w-12 text-[#1877F2]"/><div className={`h-36 w-20 border p-2 ${index===0?'border-white/25 bg-white/10':'border-[#1C1E21]/12 bg-white'}`}><div className="h-14 bg-[#1877F2]"/><div className={`mt-2 h-2 w-full ${index===0?'bg-white/20':'bg-[#1C1E21]/10'}`}/><div className={`mt-2 h-2 w-2/3 ${index===0?'bg-white/20':'bg-[#1C1E21]/10'}`}/></div></div> : category === "Web Development" ? <div className={`relative mt-8 border p-5 ${index===0?'border-white/20 bg-white/[.06]':'border-[#1C1E21]/10 bg-white'}`}><div className="flex items-end gap-2">{[42,68,54,88,72,105,92].map((height,item)=><i key={item} className="flex-1 bg-[#1877F2] transition-all duration-500 group-hover:bg-[#78B7FF]" style={{height}}/>)}</div><div className={`mt-4 flex justify-between border-t pt-3 text-[9px] uppercase tracking-[.14em] ${index===0?'border-white/15 text-white/45':'border-[#1C1E21]/10 text-[#1C1E21]/38'}`}><span>Performance</span><span>98 / 100</span></div></div> : <div className="relative mt-8 grid grid-cols-3 gap-2">{["Aa","◫","↗","#","◉","+"].map((item,i)=><div key={i} className={`grid aspect-square place-items-center border text-lg font-semibold transition group-hover:-translate-y-1 ${i===4?'bg-[#1877F2] text-white':index===0?'border-white/20 bg-white/[.06] text-white/70':'border-[#1C1E21]/10 bg-white text-[#1C1E21]/55'}`}>{item}</div>)}</div>}
    <div className={`absolute inset-x-6 bottom-5 flex items-center justify-between border-t pt-4 text-[9px] font-semibold uppercase tracking-[.17em] ${index===0?'border-white/15 text-white/42':'border-[#1C1E21]/10 text-[#1C1E21]/35'}`}><span>Opus field note</span><span>System / {String(index+1).padStart(2,"0")}</span></div>
  </div>;
}

function BlogsHeader({menuOpen,setMenuOpen}:{menuOpen:boolean;setMenuOpen:(value:boolean)=>void}){return <header className="fixed inset-x-0 top-0 z-50 border-b border-[#1C1E21]/10 bg-white/95 shadow-sm backdrop-blur-xl"><div className="section-shell flex h-24 items-center justify-between"><Link href="/" className="relative h-16 w-40"><Image src="/images/opus-logo.png" alt="Opus Geeks" fill className="object-contain object-left"/><span className="absolute inset-x-0 bottom-0 text-center text-[11px] tracking-[.24em]">OPUSGEEKS</span></Link><nav className="hidden items-center gap-7 text-sm lg:flex"><Link href="/">Home</Link><div className="group relative"><button className="flex items-center gap-1">Services <ChevronDown className="h-4 w-4"/></button><div className="invisible absolute left-1/2 top-8 w-56 -translate-x-1/2 translate-y-2 rounded-xl border bg-white p-2 opacity-0 shadow-xl transition group-hover:visible group-hover:translate-y-0 group-hover:opacity-100"><Link href="/app-development" className="block rounded-lg px-3 py-2 hover:bg-[#F0F2F5]">App Development</Link><Link href="/web-development" className="block rounded-lg px-3 py-2 hover:bg-[#F0F2F5]">Web Development</Link><Link href="/ux-ui-design" className="block rounded-lg px-3 py-2 hover:bg-[#F0F2F5]">UX/UI Design</Link></div></div><Link href="/portfolio">Portfolio</Link><Link href="/blogs" className="font-semibold text-[#1877F2]">Blogs</Link><Link href="/about">About</Link><Link href="/#contact">Contact Us</Link><Link href="/faqs">FAQs</Link></nav><Link href="/#contact" className="hidden rounded-full bg-[#1C1E21] px-6 py-3 font-semibold text-white lg:block">Get Started</Link><button onClick={()=>setMenuOpen(!menuOpen)} className="flex h-11 w-11 items-center justify-center rounded-full border lg:hidden">{menuOpen?<X/>:<Menu/>}</button></div>{menuOpen?<nav className="section-shell space-y-1 pb-5"><Link className="block rounded-xl px-4 py-3" href="/">Home</Link><Link className="block rounded-xl px-4 py-3" href="/portfolio">Portfolio</Link><Link className="block rounded-xl bg-[#E7F3FF] px-4 py-3 font-semibold text-[#1877F2]" href="/blogs">Blogs</Link><Link className="block rounded-xl px-4 py-3" href="/about">About</Link><Link className="block rounded-xl px-4 py-3" href="/#contact">Contact Us</Link></nav>:null}</header>}
function BlogsFooter(){return <footer className="border-t border-[#1C1E21]/10 bg-white py-12"><div className="section-shell flex flex-col gap-7 md:flex-row md:items-center md:justify-between"><div><div className="relative h-16 w-44"><Image src="/images/opus-logo.png" alt="" fill className="object-contain object-left"/></div><p className="mt-3 text-sm text-[#1C1E21]/50">Ideas for better products, stronger brands, and smarter growth.</p></div><div className="flex flex-wrap gap-5 text-sm text-[#1C1E21]/55"><Link href="/portfolio">Portfolio</Link><Link href="/app-development">App Development</Link><Link href="/web-development">Web Development</Link><a href="mailto:contact@opusgeeks.com">contact@opusgeeks.com</a></div></div></footer>}
