"use client";

import Image from "next/image";
import Link from "next/link";
import { AnimatePresence, motion, useScroll, useSpring } from "framer-motion";
import { ArrowRight, ChevronDown, CircleHelp, Search, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";

type Faq = { category: string; q: string; a: string };
const faqs: Faq[] = [
  {category:"Web Development",q:"What types of websites do you develop?",a:"We develop ecommerce stores, business websites, portfolio sites, blogs, web applications, and other tailored digital experiences."},
  {category:"Web Development",q:"Do you offer custom website development?",a:"Yes. We provide custom website development tailored to your requirements, audience, workflows, and business goals."},
  {category:"Web Development",q:"What technologies do you use for website development?",a:"Our team works across HTML, CSS, JavaScript, PHP, Python, and established platforms and frameworks including WordPress, Drupal, Joomla, and Magento."},
  {category:"Web Development",q:"How long does it take to develop a website?",a:"The timeline depends on project complexity and requirements. We establish realistic milestones with every client and keep delivery progress visible."},
  {category:"Web Development",q:"Do you provide website maintenance services?",a:"Yes. Our maintenance services keep websites updated, secure, reliable, and performing optimally over time."},
  {category:"Web Development",q:"Can you redesign an existing website?",a:"Absolutely. We redesign and modernize existing websites to improve aesthetics, functionality, performance, conversion, and user experience."},
  {category:"Web Development",q:"What is your approach to website design and development?",a:"We use a collaborative process and involve clients from discovery and concept development through design, engineering, testing, and deployment."},
  {category:"Web Development",q:"Do you provide responsive website design?",a:"Yes. Responsive behavior is built into our process so websites work smoothly across mobile, tablet, laptop, and desktop screens."},
  {category:"Web Development",q:"How much does website development cost?",a:"Cost depends on complexity, features, integrations, content, and customization. We provide a tailored quote after understanding your requirements."},
  {category:"Web Development",q:"Do you offer support after launch?",a:"Yes. We provide ongoing support for issues, updates, improvements, security, and guidance on maximizing website performance."},
  {category:"App Development",q:"What types of apps do you develop?",a:"We develop iOS, Android, native, hybrid, and cross-platform mobile applications for a wide range of business needs."},
  {category:"App Development",q:"Do you provide custom app development services?",a:"Yes. Every app can be tailored around your users, unique requirements, operational needs, and commercial goals."},
  {category:"App Development",q:"What technologies do you use for app development?",a:"Our capabilities include Swift, Kotlin, React Native, Flutter, Xamarin, and other technologies selected according to product requirements."},
  {category:"App Development",q:"How long does it take to develop an app?",a:"Timelines depend on product scope, platforms, features, integrations, and testing. We agree on realistic milestones before development begins."},
  {category:"App Development",q:"Do you provide app design services?",a:"Yes. We create intuitive, user-friendly interfaces and complete UX flows designed to improve engagement and satisfaction."},
  {category:"App Development",q:"Can you develop for both iOS and Android?",a:"Yes. We build for both platforms and can recommend native or cross-platform delivery based on performance, budget, and timeline needs."},
  {category:"App Development",q:"Do you offer app maintenance and support?",a:"Yes. We keep applications updated, secure, compatible with platform changes, and performing reliably after launch."},
  {category:"App Development",q:"What is your app development approach?",a:"We follow an agile, collaborative process with rapid iteration and often prioritize a focused MVP to reach the market efficiently."},
  {category:"App Development",q:"How much does app development cost?",a:"Cost varies with features, platforms, integrations, design complexity, and customization. We quote after understanding the product scope."},
  {category:"UI/UX Design",q:"Why is UI/UX design important for my website or app?",a:"Strong UI/UX improves usability, engagement, retention, customer satisfaction, and the likelihood that a digital product achieves its business goals."},
  {category:"UI/UX Design",q:"What UI/UX design services do you offer?",a:"We offer user research, information architecture, wireframing, prototyping, visual design, design systems, usability testing, and interface implementation support."},
  {category:"UI/UX Design",q:"Do you provide custom UI/UX design solutions?",a:"Yes. Our design solutions are tailored to your product requirements, target audience, brand identity, and business objectives."},
  {category:"UI/UX Design",q:"What is your design process like?",a:"We research user needs, map journeys, create wireframes and prototypes, validate ideas, refine through feedback, and prepare polished interfaces for implementation."},
  {category:"UI/UX Design",q:"How do you ensure the design meets our requirements?",a:"Clients participate throughout the process so decisions stay aligned with their vision, brand, users, constraints, and measurable goals."},
  {category:"UI/UX Design",q:"Do you conduct usability testing?",a:"Yes. Testing helps us identify friction and usability problems before launch, then improve flows using evidence rather than assumptions."},
  {category:"UI/UX Design",q:"What tools do you use for UI/UX design?",a:"Our team uses industry-standard tools including Figma, Sketch, Adobe XD, InVision, and supporting research and collaboration platforms."},
  {category:"UI/UX Design",q:"How much does UI/UX design cost?",a:"Pricing depends on scope, number of flows and screens, research depth, complexity, and required deliverables. We provide a custom quote after discovery."}
];
const categories=["All","Web Development","App Development","UI/UX Design"];

export default function FaqPage(){
  const [active,setActive]=useState("All"); const [query,setQuery]=useState(""); const [open,setOpen]=useState<number|null>(0);
  const {scrollYProgress}=useScroll(); const progress=useSpring(scrollYProgress,{stiffness:110,damping:28,mass:.25});
  const visible=useMemo(()=>faqs.filter(item=>(active==="All"||item.category===active)&&(item.q+item.a).toLowerCase().includes(query.toLowerCase())),[active,query]);
  return <main className="min-h-screen bg-[#F0F2F5] text-[#1C1E21]"><motion.div style={{scaleX:progress}} className="fixed inset-x-0 top-0 z-[70] h-[3px] origin-left bg-[#1877F2]"/><SiteHeader/>
    <section className="relative overflow-hidden border-b border-[#1C1E21]/10 bg-white pt-24"><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(rgba(24,119,242,.07)_1px,transparent_1px),linear-gradient(90deg,rgba(24,119,242,.07)_1px,transparent_1px)] [background-size:64px_64px]"/><div className="section-shell relative grid min-h-[570px] items-center gap-10 py-14 lg:grid-cols-[1.05fr_.95fr]"><motion.div initial={{opacity:0,y:25}} animate={{opacity:1,y:0}}><p className="flex items-center gap-2 text-sm font-semibold uppercase tracking-[.2em] text-[#1877F2]"><Sparkles className="h-4 w-4"/>Clarity before commitment</p><h1 className="mt-6 text-balance text-5xl font-semibold leading-[1.02] md:text-7xl">Frequently asked <span className="text-[#1877F2]">questions.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#1C1E21]/60">From project inquiries to technical support, find clear answers about our services, process, timelines, pricing, and ongoing support.</p><label className="mt-9 flex max-w-lg items-center gap-3 rounded-full border border-[#1C1E21]/10 bg-[#F0F2F5] px-5 py-4 shadow-sm"><Search className="h-5 w-5 text-[#1877F2]"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search a question..." className="w-full bg-transparent outline-none"/></label></motion.div><motion.div initial={{opacity:0,x:35}} animate={{opacity:1,x:0}} className="relative mx-auto h-[430px] w-full max-w-[500px]"><div className="absolute inset-8 rounded-full bg-[#1877F2]/10"/><motion.div animate={{y:[0,-9,0],rotate:[-1,1,-1]}} transition={{duration:.8}} className="absolute inset-0"><Image src="/images/faq-hero.png" alt="Frequently asked questions" fill priority className="object-contain drop-shadow-[0_30px_45px_rgba(28,30,33,.18)]"/></motion.div><div className="absolute bottom-5 left-0 rounded-xl border border-[#1877F2]/15 bg-white p-4 shadow-xl"><p className="text-xs uppercase tracking-[.18em] text-[#1877F2]">Knowledge base</p><b className="mt-1 block">{faqs.length} practical answers</b></div></motion.div></div></section>

    <section className="py-20 md:py-28"><div className="section-shell"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#1877F2]">Got questions?</p><h2 className="mt-4 text-balance text-4xl font-semibold md:text-6xl">We&apos;ve got answers.</h2></div><p className="max-w-xl text-lg leading-8 text-[#1C1E21]/55">Transparency helps you make informed decisions. Browse by service or search for exactly what you need.</p></div><div className="mt-9 flex gap-2 overflow-x-auto pb-2">{categories.map(category=><button key={category} onClick={()=>{setActive(category);setOpen(null)}} className={`whitespace-nowrap rounded-full px-4 py-2.5 text-sm font-semibold transition ${active===category?"bg-[#1877F2] text-white":"border border-[#1C1E21]/10 bg-white text-[#1C1E21]/55"}`}>{category}</button>)}</div>
      <div className="mt-10 grid gap-3 lg:grid-cols-2 lg:items-start">{visible.map((item,index)=><div key={item.q} className="overflow-hidden rounded-xl border border-[#1C1E21]/10 bg-white shadow-sm"><button onClick={()=>setOpen(open===index?null:index)} aria-expanded={open===index} className="flex w-full items-center justify-between gap-5 p-5 text-left"><span><small className="mb-2 block font-semibold text-[#1877F2]">{item.category}</small><b className="text-base md:text-lg">{item.q}</b></span><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full transition ${open===index?"rotate-180 bg-[#1877F2] text-white":"bg-[#F0F2F5] text-[#1C1E21]/55"}`}><ChevronDown className="h-5 w-5"/></span></button><AnimatePresence initial={false}>{open===index?<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}}><p className="border-t border-[#1C1E21]/10 px-5 py-5 leading-7 text-[#1C1E21]/60">{item.a}</p></motion.div>:null}</AnimatePresence></div>)}</div>{visible.length===0?<div className="mt-12 rounded-2xl border border-[#1C1E21]/10 bg-white p-10 text-center"><CircleHelp className="mx-auto h-10 w-10 text-[#1877F2]"/><h3 className="mt-4 text-xl font-semibold">No matching answer found</h3><p className="mt-2 text-[#1C1E21]/55">Try another search or ask our team directly.</p></div>:null}</div></section>
    <section className="bg-[#1877F2] py-16 text-white"><div className="section-shell flex flex-col gap-7 md:flex-row md:items-center md:justify-between"><div><p className="text-sm uppercase tracking-[.2em] text-white/65">Still curious?</p><h2 className="mt-3 text-balance text-4xl font-semibold md:text-5xl">Can&apos;t find what you&apos;re looking for?</h2><p className="mt-3 text-white/70">Your questions are our priority. Reach out and we&apos;ll help directly.</p></div><Link href="/contact-us" className="inline-flex shrink-0 items-center gap-3 self-start rounded-full bg-white px-6 py-4 font-semibold text-[#1877F2]">Ask our team <ArrowRight className="h-5 w-5"/></Link></div></section><SiteFooter/>
  </main>;
}
